### ISSUE TITLE
Recover Vessels Straight To Inventory

### ISSUE THREAD

**Issue by magico13** [magico13/KCT#10]
Pretty self-explanatory. You should have the ability to recover vessels straight into the warehouse/inventory without rebuilding and without being able to make repairs. Not sure how to handle fuel levels though. Probably let you fill them up for no time.

**Comment by fingerboxes** [comment]
Can you point me at the entry point for this?

**Comment by magico13** [comment]
I'm not home right now, but I'll try to explain. The primary starting point
is a button on the build list GUI that's available when the vessel can be
recovered. It creates a BuildListVessel from a Vessel through the
appropriate constructor, then calls the function that KSP uses for the drop
down recover button above the altimeter. That should give you a starting
point. Let me know if you have more questions.
