### ISSUE TITLE
KSC Switcher Default Site

### ISSUE THREAD

**Issue by magico13** [magico13/KCT#113]
Currently KCT uses the "Stock" KSC until the KSC is switched in the map view. People seem to forget to go in and switch to a site until after they do a few launches, resulting in everything being lost. If we can either poll KSCSwitcher to get the "default" site and use that instead, or if we can shift everything into the first site that's selected, those would be better than losing access to everything.

**Comment by kurie** [comment]
I'm using KCT for the first time (along with all of the realism overhaul mods) and this happened to me. Also, possibly a related problem: I can't upgrade R&D at any other KSC after I switched it from stock. (No upgrade button in the upgrade UI, despite having 16 points available.)

**Comment by magico13** [comment]
This should be fixed with v1.3
