### ISSUE TITLE
KCT crashes badly when recovering a vehicle with failed parts from TestFlight

### ISSUE THREAD

**Issue by CorvusCorax** [magico13/KCT#114]
I'm using RealismOverhaul with RP-0 and now have both TestFlight and KCT installed.

KCT and TestFlight seem not ne be cooperating, when a part fails during flight, the later recovered vehicle becomes unusable and crashes KCT (it can only be scrapped)

Normal behaviour:
- Design a recoverable rocket or airplane with some engine on that can fail (for example WAC aerobee)
- Build it with KCT
- Launch it but stop flying before any component fails (or not have TestFlight active)
- Recover it
- Game behaves normal

Problem reproduction:
- Design a recoverable rocket or airplane with some engine on that can fail (for example WAC aerobee)
- Build it with KCT
- Launch it
- Fly until after some component fails (engine failure or explosion) then land
- Recover the vehicle

Expected behaviour:
- Vehicle can be launched again, and failed components are still non-working
or
- Vehicle can be edited in VAB/SPH and failed components can then be exchanged for working ones (like it can be done with engines that have 0 ignitions left)

Actual behaviour:
- On launching a vehicle again that had failed components, the game crashes
or
- On editing a vehicle in VAB/SPH (using the "edit" command from KCT) the following error message appears:
Error Loading KCT Data
ERROR! An error occurred while loading KCT data. Things will be seriously broken! Please report this error to the KCT forum thread and attach the logfile. The game will be UNPLAYABLE in this state! <Understood>

Reproducable with:
KSP 1.0.5
TestFlight 1.4.0.2
KCT1.3.0
(latest CKAN versions as of 2016-01-08)

I am currently in the process of assembling a clean install with the minimum amounts of mods needed to recreate the issues so I can give you a somewhat clean logfile...

**Comment by CorvusCorax** [comment]
RP-0 or RO is not needed for reproduction. The issue is reproducable with stock + KCT + TestFlight only.

Steps to reproduce:
- install fresh new ksp 1.0.5 + KCT + TestFlight + TestFlight Config (stock)
- start new science game (havent tested sandbox, issue definitely exists in science and career)
- research just enough for the first liquid fuel engine and fuel tank and design a vessel with a few of those that stays stationary (a manned engine test stand)
- build and launch
- fast forward until parts fail bad (failure to ignite on an engine is not enough, since thats not permanent (can still be ignited again in stock), when failing parts start exploding, you're good)
- recover vessel with KCT
- edit vessel -- > leads to afforementioned error message


[Player.log.txt](https://github.com/magico13/KCT/files/82774/Player.log.txt)
[KSP.log.txt](https://github.com/magico13/KCT/files/82777/KSP.log.txt)

**Comment by CorvusCorax** [comment]
in stock the same verbouse error message also appears when actually launching such a once recovered vehicle - together with an epic fail of the physics engine and GUI - i needed to hard-close the game to recover

**Comment by CorvusCorax** [comment]
![error](https://cloud.githubusercontent.com/assets/569222/12199958/3b428f0c-b61c-11e5-8991-98ea7b30351b.png)

**Comment by magico13** [comment]
Thank you for the very detailed report. I'll do some testing on my own tonight and/or tomorrow. What the recover code is doing is trying to take a Vessel and all of its Module data and turn it back into a craft file, which is then turned back into a Vessel. KSP isn't designed to do this, so it frequently has problems. I might just have to reset all the TestFlight modules back to their original states, but I won't know until I run some tests.

In the meantime, you'll just have to use the stock recover mechanic and build new crafts from the parts added to the inventory. I'll let you know when I find a solution.

**Comment by CorvusCorax** [comment]
I think this is the exception triggered when re-editing/spawning the craft:
```
Exception loading ScenarioModule KerbalConstructionTimeData: System.NullReferenceException: Object reference not set to an instance of an object
  at ShipConstruct.SaveShip () [0x00000] in <filename unknown>:0 
  at KerbalConstructionTime.KCT_BuildListVessel..ctor (.ShipConstruct s, System.String ls, Double bP, System.String flagURL) [0x00000] in <filename unknown>:0 
  at KerbalConstructionTime.KCT_Utilities.RecalculateEditorBuildTime (.ShipConstruct ship) [0x00000] in <filename unknown>:0 
  at KerbalConstructionTime.KerbalConstructionTime.DelayedStart () [0x00000] in <filename unknown>:0 
  at KerbalConstructionTime.KerbalConstructionTimeData.OnLoad (.ConfigNode node) [0x00000] in <filename unknown>:0 
  at ScenarioModule.Load (.ConfigNode node) [0x00000] in <filename unknown>:0 
  at ScenarioRunner.AddModule (.ConfigNode node) [0x00000] in <filename unknown>:0 
```
but I assume the problem might occur sooner on recovery?

My guess would be that TestFlight does something weird to failed parts - (maybe only those that exploded?)  to store the testflight relevant metadata and failure state - and KCT fails to copy those parts and/or their metadata into the craftfile correctly

I also gaabbed the KCT_Backup.sfs from the saves folder, in case that helps in any way
[KCT_Backup.sfs.txt](https://github.com/magico13/KCT/files/82878/KCT_Backup.sfs.txt)

**Comment by magico13** [comment]
If a part is actually being destroyed and it's a symmetry part then that could be the cause of the issue (see #82 ).

That problem wouldn't occur until the resulting craft file is loaded, which only happens once you edit or launch it. I can at the very least add additional tests when trying to recover to prevent the creation of a bugged craft. Then you won't be able to mess up your save on accident at least, assuming I can't fix the bug itself.

Could you upload the save from right after you recover the craft (just recover and then exit to the main menu)? That'll have the craft file saved in so I can see if there's anything obvious in there (the smaller you can make the craft, the better). Doesn't matter too much though, since it seems this will be easy to reproduce once I get home.

**Comment by CorvusCorax** [comment]
[persistent.sfs.txt](https://github.com/magico13/KCT/files/82903/persistent.sfs.txt)
(save game)
[test2.craft.txt](https://github.com/magico13/KCT/files/82904/test2.craft.txt)
(original craft file as saved from editor (not buggy))

**Comment by CorvusCorax** [comment]
btw the save isn't completely corrupted. The recovered craft still can be scrapped as a workaround, but regardles which workaround is chosen - weither its scrapped or "recovered the stock way" and rebuilt - it takes a month to rebuild a spaceplane even from existing parts from inventory versus "instant" when recovered. That can have quite dire implications regarding contract deadlines 

would it be possible as a "programmatic workaround" to simply dump the symmetry information from a part where one of the symmetric components is missing? a set of 8 engines in symetry would then become 7 individual engines when recovered with one of them missing (as I can see from the craft file one would only have to remove the sym=... lines - right?)

**Comment by magico13** [comment]
> to simply dump the symmetry information from a part where one of the symmetric components is missing

That's the hope, assuming that's the cause of the issue. I won't know until I try it though, but it's certainly one of the things I'm going to try.

**Comment by CorvusCorax** [comment]
I think all of the parts that I had issues with had some sort of symmetry. I'm trying to see what happens if I remove the sym= lines from the test2 file in the KCS section in the persistent.sfs

**Comment by CorvusCorax** [comment]
yep, that works. when the "sym= ... " lines are removed from the KCT_DataStorage area in persistent.sfs, and I then load the savegame, I can both edit and fly the vehicle.

So the workaround against the symmetry bug would work. Could it be that some sym=... lines refer to non-existent parts? (I only deleted them, didn't count them) maybe its sufficient to get rid of those that refer to exploded parts

**Comment by CorvusCorax** [comment]
THAT WAS IT :-)))))
In the persistent.sfs that crashes, in the outer ring of 8 "FuelTankSmall"s  (of which one is missing) the "sym="  lines still reference 
```
sym = fuelTankSmall_4294201132
```
however that fuel tank does not exist anymore. (It exploded thanks to TestFlight)

interestingly, sym= lines in the engines dont reference the missing engine anymore, (the part got clipped off when the tank exploded and was not recovered) only the part that testflight exploded did.

deleting all these sym=... references to nonexisting tanks fixed the savegame.

As such the fix to this (and the fix to the other symmetry issues) should be pretty straight forward. Delete all sym=... references to nonexisting parts.

I think you could do that either at save-time or later at load time (the latter might be easier by means of exception handling but thats up to you)

**Comment by magico13** [comment]
Thank you very much for looking into this! Seems like it should be a simple fix to add. I should be able to implement the fix when the craft is first recovered (that way we don't store a potentially buggy craft at any point in time), though I may add a check at load as well in case something manages to slip through. I'll still add in some additional tests when saving the ship to try to avoid any other potential bugs like this, popping up an error message rather than putting a bugged craft into the save file.
