### ISSUE TITLE
Build rate upgrade bug: Rate 2 shown when should not be

### ISSUE THREAD

**Issue by NathanKell** [magico13/KCT#119]
Using this formula:
BuildRateFormula = (1+([L]_0.25))_(([I]+1)_0.05_[N] + max(0.1-[I], 0))*sign([L]-[I])

When first starting the game, Rate 1 and Rate 2 are both shown (with 0.05 and 0.1 as the increase amounts). When Rate 1 is selected, Rate 2 disappears. When Rate 2 is selected, Rate 2 disappears _but the upgrade point is still used_.

(Desired behavior: 1 build rate per VAB/SPH tier).

**Comment by magico13** [comment]
Sounds like the rates aren't resetting after selecting a Preset, maybe.

Is this just for new games or all games? Was a previous save loaded first, or was it start KSP->start game? Are you only seeing it with that formula?

I'm not sure when I'll get a chance to look at this, but it doesn't seem like it should be too hard to track down.

**Comment by NathanKell** [comment]
I tried it on a new game, but a previous save was loaded first IIRC. I will try on a fresh start->fresh save. It's only for that first upgrade point though, so it's work-around-able, it's just that if someone puts it in the other rate by mistake it's sucked up and doing nothing until the VAB/SPH upgrades.

**Comment by NathanKell** [comment]
Fresh start of KSP, fresh save. Build Rate 2 appears and you can put one point into it. If you instead put the point in Build Rate 1, Build Rate 2 still shows up, at 0, but cannot be added to (no button).
After quitting KSP and restarting, and reloading the save, Build Rate 2 still behaves the same (shows up but no button).
