### ISSUE TITLE
Build time modifiers

### ISSUE THREAD

**Issue by NathanKell** [magico13/KCT#120]
It'd be great if KCT had a PartModule that you could add to a part to vary its BP cost, or (perhaps easier) if there were a config file (MM-accessible) that could contain a list of parts and multipliers for them.
The reasoning is: I'd like space capsules with crew capacity to not cost more, just take rather longer--but not hitchhiker pods and not aircraft cockpits.

**Comment by magico13** [comment]
That's a concern I've had for a while (see #65) but hadn't run into a situation where it was really needed until now. The simplest way I can think of implementing this would be to add a variable that has a user provided value to the "effective cost" formulas. The values for each part could be part of the Preset.

How you choose to use those variables would be up to you, you could either use them as a straight multiplier or you could have the variables replace the computed value.

example:
````
PRESET
{
general settings
{}

time settings
{}

formulas
{}

PartVariables
{
  default = 1
  mk1pod = 2.5
  ...
}
}
````

**Comment by NathanKell** [comment]
Looks good to me, yeah. That's certainly simplest and easy enough for modders too.

**Comment by magico13** [comment]
I think the solution that was added in the commit referenced above is probably sufficient, but if not feel free to open a new issue. I'm doing some cleanup of old issues.
