### ISSUE TITLE
VAB Simulation windows shrinks and can't be modified when simulation time is invalid

### ISSUE THREAD

**Issue by Baleine82** [magico13/KCT#122]
Here's the way I reproduced the bug.
- Create any new vessel in VAB
- open simulation Windows
- type "1H" (without quotes) in the simulation time

The window content should disappear, preventing you from quitting the VAB screen.

Solution found : Modifying the save to change simulation time to some string that KCT accepts.

**Comment by kaptain-kavern** [comment]
I was going to report this one...
Now i have fixed it. Thx a lot :p

**Comment by magico13** [comment]
It's on my todo list to get corrected in the next update, but I haven't had time lately to even look at any code. Thanks for taking the initiative to work around the issue in the meantime ;)

**Comment by magico13** [comment]
There aren't simulations in KCT anymore so I'm going to close this, but it sounds like an issue with MagiCore. I think it might be averted with some recent changes in MagiCore though.
