### ISSUE TITLE
Recovered vessels stuck in VAB roof

### ISSUE THREAD

**Issue by magico13** [magico13/KCT#124]
http://forum.kerbalspaceprogram.com/index.php?/topic/83342-105-kerbal-construction-time-131-011316-unrapid-planned-assembly/&do=findComment&comment=2441673

Sometimes vessels have weird positions that cause them to get stuck in the roof and can't be grabbed. Shouldn't be too hard to move them to a more convenient location (ideally touching the floor) on recover.

**Comment by baldamundo** [comment]
I think this just happened to me (except the SPH). Is there anything one can do about it besides scrapping the craft and building another?

**Comment by magico13** [comment]
I believe you can modify the craft in the save file to lower the parts, but
it's been a while since I looked at it. If you send me the save and the
craft name I can take a look tonight.

**Comment by magico13** [comment]
This was averted recently in the dev builds by limiting the max height that a recovered vessel can have. It doesn't fix the underlying problem, but it prevents it from being an actual issue.
