### ISSUE TITLE
Start sim in eccentric orbit?

### ISSUE THREAD

**Issue by jwvanderbeck** [magico13/KCT#127]
This may already be possible, but I couldn't find a way so figured I would post it here as a feature request.

I would like to be able to start a sim in an eccentric orbit for specific testing.  Preferably I would be able to, in the advanced options settings, specify both a PE and AP for the testing orbit.

**Comment by magico13** [comment]
It isn't possible as-is, but you might consider using hyperedit as well. Simulations are actually going to be phased out and [KRASH](http://forum.kerbalspaceprogram.com/index.php?/topic/133082-krash-kerbal-ramification-artifical-simulation-hub-simulation-mod-for-ksp-cost-settings-have-been-change/&do=findComment&comment=2432863) is going to become the main source for simulations fairly soon (maybe even for 1.1). I'm not sure if their simulations allow for any eccentricity (yet) but I'd suggest putting in a request over there if it doesn't.

**Comment by jwvanderbeck** [comment]
Ah that's a shame :(  But ok thanks for the heads up!

**Comment by Baleine82** [comment]
Still, if you need to simulate your specific orbit, you can also add a stage to alter your starting orbit. It'll cost you a bit more, but that'll work.
