### ISSUE TITLE
Window not displayed in 1.1.2

### ISSUE THREAD

**Issue by petersohn** [magico13/KCT#131]
I am using KSP 1.1.2 on Linux (it's the first version of 1.1 I am using, I have no info whether the same problem appears on earlier 1.1 versions) and KCT v1.3.3-pre2. When I try to open the KCT window, only the upper part of it appears. The same happens at KSC and during flight. Here is a screenshot:

http://images.akamai.steamusercontent.com/ugc/501399955315735340/6EBA3435FBC5AFD2F7BB54FD85A124A9BA406B0B/

That gray line at the upper right corner of the screen, just below the exit button is supposed to be the KCT window.

I found the following in KSP.log:

```
[EXC 17:28:44.783] MissingMethodException: Method not found: 'PopupDialog.SpawnPopupDialog'.
        UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
        UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[EXC 17:28:44.785] MissingMethodException: Method not found: 'PopupDialog.SpawnPopupDialog'.
        UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
        UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
```

**Comment by magico13** [comment]
Latest pre-release should take care of this. Feel free to reopen if that's not the case.
