### ISSUE TITLE
KCT would not start simulation, then says is corrupted after re-entering VAB

### ISSUE THREAD

**Issue by SirKeplan** [magico13/KCT#137]
pressed the button to start a KCT sim(twice i think) wasn't working, so reentered VAB. then it gave the pop up dialog telling me to report the error because KCT is broken.

64 bit Ubuntu system, KSP 1.1.2, RSS/RO/RP-0 installed.

https://dl.dropboxusercontent.com/u/46930029/Player.log(3)

**Comment by SirKeplan** [comment]
Hmm, don't worry about this too much, seems like it might have been a glitch with the craft. the cost of the craft was probably NAN at the time for some reason.

**Comment by magico13** [comment]
I'm going to close this since I'm doing some cleanup of old issues. If you see this problem, or a related one, again please let me know. Thanks.
