### ISSUE TITLE
NotSupportedException

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [magico13/KCT#142]
Changes in Contract Configurator 1.20 mean that certain reflection methods will cause NotSupportedExceptions -- see blizzy78/ksp_toolbar#39 for more details.  I can give you a PR that fixes all of the reflection calls presently in KCT (to the toolbar, Kerbal Alarm Clock, Stage Recovery...), if you haven't rewritten too much of KCT yet.

**Comment by magico13** [comment]
Shouldn't that just require updating ToolbarWrapper.cs? If so, that should be pretty straightforward for me to update while I work on getting everything else up to date.

**Comment by Kerbas-ad-astra** [comment]
Not just ToolbarWrapper, but CrewQAPI, KACWrapper, KCT_Events, KCT_Utilities, MCEWrapper, and StageRecoveryWrapper -- anything that uses that pattern of "AssemblyLoader.loadedAssemblies.SelectMany..." needs to be changed to the TypeOperation pattern.  (Maybe I should make a PR.)

**Comment by Kerbas-ad-astra** [comment]
Resolved by accepted PR #143.
