### ISSUE TITLE
Override Launch Button doesn't work

### ISSUE THREAD

**Issue by petersohn** [magico13/KCT#147]
I'm using the latest commit from the development branch and KSP 1.2.1. If the "Override Launch Button" option is set, then the "Build" option is removed from the KCT window in the editor, but the stock launch button is still disabled.

**Comment by magico13** [comment]
I'm gonna link you to the dev thread since a lot of the issues you're mentioning are discussed there. It's also where the bug reporting has primarily taken place. http://forum.kerbalspaceprogram.com/index.php?/topic/62900-kerbal-construction-timestagerecovery-dev-thread/

**Comment by magico13** [comment]
Since I didn't actually address this issue, overriding the stock button is completely broken in 1.2. it appears as if Squad made it impossible, or at least substantially more difficult, to stop the scene change from happening.

**Comment by petersohn** [comment]
OK, I wrote my findings on that thread.

**Comment by magico13** [comment]
The override launch button should be working properly now. At the time of this issue being created, it wasn't working correctly at all. If you see this behavior again, please open a new issue or report it on the forum. Thanks! (I'm doing some cleanup of old issues)
