### ISSUE TITLE
After upgrading VAB or SPH to level 3, all its rates disappear

### ISSUE THREAD

**Issue by gbesacier** [magico13/KCT#151]
After the level 3 upgrade for VAB or SPH is completed (either through waiting in-game with KCT or editing the save file), the rates for this building disappear, along with the button to create a new rate

![kct-lvl3-bug](https://cloud.githubusercontent.com/assets/2737489/25307429/efcd4c0e-27a0-11e7-849f-6e487877b015.png)

Resetting Upgrades makes the rates and the buttons reappear. If only one of VAB/SPH is at level 3, upgrading any rates of the other building (which is not at level 3 and thus unaffected), makes the level 3 building rates reappear (at the upgraded level). Upgrading either R&D rate does not.

When the rates have reappear via either of these techniques, saving and reloading will make them disappear again, entering either VAB, SPH (regardless of which one is or isn't at level 3), or tracking station will make them disappear again.

When the rates are disappeared, building a ship will displayed a NaN ETA. When the rates reappear through resetting upgrades or upgrading any not-level-3 building rate, the ship will start getting built normally.

When editing the disappeared rates in the save file, for example lowering the upgrade count in VABUpgrades{}, the upgrade points are correctly returned to the upgrade pool.

Nothing suspicious in the log.

KSP 1.2.2 (not 1.3 preview), KCT 1.3.9.0 (download from the devel branch just now)

**Comment by magico13** [comment]
I'm not seeing this on my end. You're using the version downloaded from the [build server](http://magico13.net:8080/job/Kerbal%20Construction%20Time%20Beta/) (latest is 1.3.0.19)?  Can you upload the log anyway? It contains more info than just exceptions and might have something useful.

![level3](https://cloud.githubusercontent.com/assets/5289685/25308758/f8fa2098-2789-11e7-8a1d-1bffde5ba201.png)

**Comment by gbesacier** [comment]
I didn't noticed the DLL wasn't on Github (which is correct, compiled binaries shouldn't be under revision control, but so many projects do it anyway...). It works correctly with the last DLL, sorry for the trouble.

**Comment by magico13** [comment]
Sounds like this is working fine now. I'm cleaning up old issues, so I'm going to close this. Please feel free to let me know if you see this behavior again. Thanks!
