### ISSUE TITLE
Simulation Camera Issue

### ISSUE THREAD

**Issue by chickenswag101** [magico13/KCT#153]
So the mod works but when I go into simulation and at the launch pad, I'm not allowed to pan the camera around or zoom in. Everything works fine like how a sim is supposed to go but the camera thing doesn't work. I'm using RO and RP-0

**Comment by magico13** [comment]
KCT no longer has simulations. Are you sure you're not using KRASH?

**Comment by chickenswag101** [comment]
[http://imgur.com/a/YQnuG](url)

**Comment by chickenswag101** [comment]
http://imgur.com/a/YQnuG

**Comment by Patrykz94** [comment]
You must be using an older version of the game and mod. Try installing KRASH which is now the main simulations mod.

**Comment by chickenswag101** [comment]
ok ,but i am using ksp 1.2.2 and latest of that mod
