### ISSUE TITLE
Inactive Kerbals

### ISSUE THREAD

**Issue by NathanKell** [magico13/KCT#158]
Quick question--does KCT properly skip inactive kerbals when giving you a crew selection list? The same functionality that has them inactive from g forces can be used to keep them inactive for months at a time, but if KCT doesn't know about it it might be problematic. :)

(Apologies for not checking source, but I hoped this'd be an easy question to answer, and far faster than me digging)

**Comment by magico13** [comment]
Someone else had asked for that in the past so I'm pretty sure it does. This is roughly where that would be: https://github.com/magico13/KCT/blob/development/Kerbal_Construction_Time/KCT_GUI.cs#L1317

I'm assuming it's just the inactive bool that needs checked? In which case it should work fine.

**Comment by NathanKell** [comment]
Yep! <3
