### ISSUE TITLE
Stops time warp even when 'ForceStopWarp = False'.

### ISSUE THREAD

**Issue by Rodhern** [magico13/KCT#165]
In one of the development builds for KSP 1.3 I have turned "stop timewarp" off in the settings. Whenever a vessel is built the timewarp is reset to 1 anyway. Don't know if the issue is still there in the newest version, but it may be worth a look.
Edit:
Oops, never mind, now it is working again. I thought it would be enough to do a scene change, but I guess it wasn't.

**Comment by magico13** [comment]
It's turning off just fine for me even without a scene change. It should start obeying that setting as soon as you press the Save button. Do you want me to keep looking into this/do you want to try it again? If not then I'll close this.

**Comment by Rodhern** [comment]
Let us close this for now. I must have messed up my install a little, I am getting some warp stops and others not. I will install KAC, disable the completed messages and do a more usual style setup.
