### ISSUE TITLE
Null reference exception in FixedUpdate (ver. 1.3.0.32).

### ISSUE THREAD

**Issue by Rodhern** [magico13/KCT#166]
My log shows quite a bit of these:
[EXC 03:27:15.520] NullReferenceException: Object reference not set to an instance of an object
	KerbalConstructionTime.KCT_Utilities.ProgressBuildTime ()
	KerbalConstructionTime.KerbalConstructionTime.FixedUpdate ()
	UnityEngine.Debug:LogException(Exception)
	KerbalConstructionTime.KerbalConstructionTime:FixedUpdate()

**Comment by magico13** [comment]
Can you upload the full log? It sounds like it's trying to progress the build time on something that it shouldn't be (a corrupted craft maybe?) and since FixedUpdate happens very frequently it'll just spam the log.

**Comment by Rodhern** [comment]
I don't know how much there is to see, but sure, here is a log with som NREs in it:
http://www.act-consult.net/Rodhern/Games/KSP/Temp1/KSP.log.2017-07-24.zip

**Comment by magico13** [comment]
It's due to an incompatibility with EditorTime. I've seen it before but I haven't gotten a chance to figure out what exactly it's upset about.

**Comment by magico13** [comment]
Should be corrected in build 33. I also made some minor updates to EditorTime so you might want to grab the latest build of that as well. Feel free to reopen this if you're still seeing the issue.
