### ISSUE TITLE
Latest build: Tag from dev, but built from master?

### ISSUE THREAD

**Issue by NathanKell** [magico13/KCT#173]
Tag (and thus source) include the RO requested changes, but the dll appears not to.

Which should be correct? :)

**Comment by magico13** [comment]
I think I uploaded something old on GitHub. Best bet is to grab it straight
from the build server here:
http://magico13.net:8080/job/Kerbal%20Construction%20Time%20Beta/

**Comment by NathanKell** [comment]
Ah thanks! I rebuilt it locally and it's all good, so now that you're aware I'm gonna go ahead and close this. :)

Thanks, and sorry about dropping off the face of the earth re: the RP-0 changes!
