### ISSUE TITLE
Severe Lag when Right-clicking in Editor on Procedural Fairing base with Tweakable Everything

### ISSUE THREAD

**Issue by magico13** [magico13/KCT#41]
It may sound like a very specific issue, but it's rooted in a deeper issue where right clicking causes the vessel updated event to fire a ridiculous number of times, meaning KCT recalculates build times a ridiculous number of times.

Check this reddit comment stream for more details and an example craft: http://www.reddit.com/r/KerbalSpaceProgram/comments/2u60lg/deploying_communications_satellites_the_hard_way/co622wl?context=3 (thanks MaturinTheTurtle)

I'm not sure whether these are occurring multiple times during a single Update, but if it is the fix is simple: restrict the call to be once per update. Then you can call that event a billion times in a frame but KCT will only recalculate once. I don't expect that this will have issues with things being out of sync (since you're likely not making a bunch of changes per frame) but it is possible. At the very least, everything is recalculated when you press the build button. Perhaps I should also recalculate when the stock launch button is pressed.

**Comment by jefferyharrell** [comment]
I have a configuration of mods that demonstrates the issue, so I tested this DLL with it:

http://magico13.net:8080/job/Kerbal%20Construction%20Time%20Development/66/artifact/Kerbal_Construction_Time/obj/Debug/KerbalConstructionTime.dll

It *helped* but didn't eliminate the problem. So I think you're on the right track. To produce the problem I started with a Procedural Fairings interstage adapter, then put a MechJeb-bearing part on top of it, then right-clicked the interstage. Before installing the development-build DLL, my frame rate would've dropped severely. With the development-build DLL, it only dropped *some.* I don't have an FPS meter or anything, but at a guess I'd say it dropped from 60 frames a second down to 30 frames a second, maybe? Just a guess.

Note please that this problem vanishes entirely if I make sure the Tweakable Everything part module ModuleTweakableDecouple does not get added to the ProceduralFairingAdapter part. So I don't think this is entirely y'all's problem. I think it's possible that something in ModuleTweakableDecouple is causing the ShipModifiedEvent to get fired every physics frame, or something along those lines. But I really have no idea what I'm talking about.

**Comment by magico13** [comment]
I think I mentioned it in the reddit thread, but not on here, but for whatever reason the OnShipModified function gets called once for every tweakable thing on a part. It apparently gets exasperated with TweakableEverything. I'm not sure if they're calling that event all the time on purpose or are somehow triggering it on accident, but at least KCT should only recalculate once per frame rather than on every single call.

Btw, this is the sort of thing that might be an issue in KSP v1.0 if the Engineer Report is recalculated every time a part is added/removed.

I could probably limit KCT to recalculating at most every 5-10 frames instead of at most every 1 frame as a temporary fix. I'll see if I can find anything in their code that's triggering it.

Btw, you can use [FRAPS](http://www.fraps.com/) to view FPS (even the free trial). I'm sure there are other programs as well. It'd be nice to see that info, but it isn't really necessary. Thank you for testing though!

**Comment by jefferyharrell** [comment]
I'm a Mac person, so no FRAPS for me. There are ways to show the frame rate during play, but I've just never availed myself of any of them. Never needed to.

I just got through doing another test of sorts, and it seems the amount by which the in-game frame rate drops is proportional to the size of the vessel. When it's just an interstage adapter and a probe body, I get a very small performance impact. On an actual rocket with a few dozen parts, the performance impact is greater. I guess that's consistent with your mod doing some iterative operation multiple times when it really only needs to be doing it once.

By the way, have you actually been able to reproduce the problem? I don't think I've seen it mentioned whether or not anybody else has been able to reproduce it. I tried to be really rigorous in narrowing it down, but I still only narrowed it down to *four* mods all colliding, so I'm not completely confident I trouble-shot it adequately.

**Comment by magico13** [comment]
I haven't taken the time to set up a test environment with those mods yet, but the redditor in the first post of this thread narrowed it down to Procedural Fairings, KCT, and Tweakable Everything. It's possible it will happen for things without PF, but that wasn't tested. It seems to be most noticeable at least with fairing bases for whatever reason.

I know 100% what causes the slowdown, but I don't know what is causing the thing that causes the slowdown (precisely, in code). The reason things get slow is that every time the ship is modified, KCT has to save it to a ConfigNode so it can recalculate the total BP value of the craft. The event that KCT listens to is apparently being called nonstop by the PF+Tweakable Everything combination, resulting in a crap ton of calculations being done every frame. That's made worse by the fact that at least one part is a procedural part, which has special rules in KCT and thus has some extra code.

The saving and then parsing is the biggest CPU drain and is on KCT's side, but it isn't a problem under "normal" gameplay conditions where it's called infrequently. The "fix" as implemented just makes it so it doesn't recalculate multiple times in a single frame, but if that code is being called multiple times a frame, every frame, it will certainly experience issues. Unfortunately, I need to listen to that event because I need to know when fuel levels and other things are changed.

I can add some more throttling and try to optimize the code a bit more (without a total rewrite of that section though, which is touched by many other places, it's still going to be fairly inefficient). One possible fix that I kind of like, now that I think of it, would be to have each call to the OnShipModified event just set a flag saying "Hey, I want an update" and then every N frames check that flag (where N is possibly configurable, but by default is on the order of 10 to 20) and recalculate. That still requires it to be requested, but means it won't have nearly as large of an impact. Sure, optimizing KCT's code would help reduce the lag, but dividing the number of calls per second by 10 or more will likely have a bigger impact for less work. The real question for me is, why is that event being fired non-stop (which is an issue on the PF/TE side)?


I'm not really going to be at a computer where I can do this today, so it'll have to wait until tomorrow at the earliest (or maybe late tonight if I'm lucky) unless fingerboxes does another surprise pull request.

**Comment by fingerboxes** [comment]
@jefferyharrell - I don't have a test environment for this bug set up. Please test this fix.

https://github.com/fingerboxes/KCT/releases/tag/test0

**Comment by fingerboxes** [comment]
@jefferyharrell - Please try this fix. I don't have a test environment.

https://github.com/fingerboxes/KCT/releases/tag/test1

**Comment by jefferyharrell** [comment]
The DLL tagged test0 improved things significantly. The problem still exists, but subjectively it's a lot less intrusive. Now when I have the right-click menu open on a PF interstage part to which a MechJeb part is attached (I can't believe how obscure this is), the frame rate is fine except for "hiccups" every one to three seconds or so. I only notice this happening if I literally sit there with the menu open and watch the background animations, which is not something I'd do in real life. In real life, I'd open the right-click menu, orbit or track the camera to get the right control to a place where I can click it, then click it, then I'd be done using that menu. I found this to be entirely acceptable on a 75-part rocket, which is neither the biggest nor smallest but I guess a decent enough representative average.

The test1 DLL seemed to be more or less the same. It might have performed slightly better, but only slightly.

Weirdly though, in both cases the toolbar icon (Blizzy's) rendered as a purple square instead of the normal toolbar icon. I'm using Active Texture Management and the toolbar icon textures are compressed without mipmaps. When I use the DLL that's bundled up in the Kerbal_Construction_Time-1.1.2.zip file, the toolbar icon renders fine. I have *no* idea what that could be.

**Comment by magico13** [comment]
Oh! The icons folder got renamed to Icons (capital i) somewhere in there so it can't find the icon.

**Comment by fingerboxes** [comment]
Can you do me a favor and try the same situation without KCT installed (only the other mods in the problem configuration)?

I ask this because this is probably *literally* as good as it is going to get with KCT, and I suspect the remaining performance issues will have more to do with the other two mods. The test1 dll is only allowed to update the cost one per second, and that execution is not tied to to event call stack at all (it executes after all of the TE/PE stuff is done).

**Comment by fingerboxes** [comment]
The next attempt to fix this is going to involve figuring out how to detect when the tweakable menu is open, and pausing recalculation until it closes. NFC how to do that, and probably will require some data exposed by TE.

**Comment by jefferyharrell** [comment]
I renamed the "icons" (little eye) folder to "Icons" (big eye) and the purple square problem went away.

I also tried the experiment on a copy of my game with KCT uninstalled. If I open the tweak menu on the interstage adapter, the little hiccups I'd see with KCT installed aren't there. But again, and I can't emphasize this strongly enough, I have to *really look* to see those little hiccups. In normal VAB use, I doubt I would notice them—maybe as a slight lag when orbiting the camera at most, and KSP is hardly free of that even in the unmodded game—so I consider the test1 DLL to be entirely live-with-able. My intention is to add it to my main game (after backing that sucker up nine ways from Sunday) and play with it as usual.

As far as pausing recalculation, I know you didn't ask, but I'm kind of of two minds about that. I play with Procedural Parts to the exclusion of all other similar parts, so I frequently find myself with the tweak menu open nudging parameters this way and that while watching, for instance, MechJeb's dV estimates. I can imagine a situation in which somebody might want to nudge a parameter this way or that while watching KCT's build estimates in the same way, and having to click, change, close to see the effect could get old real fast.

But that's just something for you guys to think about. It's y'all's mod. I just play with it.

Thanks for working on this problem. You've literally make this mod usable for me, and that means a lot.

**Comment by magico13** [comment]
I don't think we'll need to turn off updates while the tweak window is open, you'll just have to live with an up to one second delay, which probably isn't too bad since the things you're tweaking aren't usually going to be focused on build times as their first priority (usually it'll be TWR, dV, cost, etc. Waiting a second for build times to update won't be that bad).

**Comment by toadicus** [comment]
I have done a little looking around, and I don't think I'm doing anything to exacerbate this except by adding more FloatRange tweakables to things, which I'm pretty sure will each fire onEditorShipModified at least twice when the part action menu is spawned (i.e. when the right click happens), and also each time the value is changed (so if the slider is being dragged around, possibly dozens to hundreds of times per second).  If it's warranted, I'm happy to look closer if you can think of anything I can do to help. :)

**Comment by jefferyharrell** [comment]
Just to clarify the problem, the lag happens just when the right-click menu is *open.* You don't have to change any of the controls in it. It's really very weird.

**Comment by magico13** [comment]
Thanks for taking a look. I'm not sure if there's anything you can change, it's probably just exasberated by the stock game's handling of those menus. By adding throttling on our side it should prevent the lag. I don't know why that event is called so frequently even if nothing changes.

**Comment by jefferyharrell** [comment]
Oh, also to clarify: I've been using the test build of the KCT DLL since whenever I installed it; three days ago I guess, according to the time stamps here. I haven't had any problems related to this issue or anything else. Well. Unless you count wasting ten days building a rocket that I had to dump into the sea. But let's not dwell on who forgot to put a docking adapter where. Point is, my game has been stable.

**Comment by toadicus** [comment]
Potentially relevant: I whipped up this [tiny plugin](http://hastebin.com/uruwudetud.avrasm) to troubleshoot.  Completely vanilla KSP and TE-only KSP do not spam onEditorShipModified when action windows are open.  I've got to go be a responsible parent now, but if anyone wants to continue troubleshooting, you can compile it yourself or go grab a DLL [here](http://ksp.hawkbats.com/dev/onEditorShipModifiedSniffer.dll).
