### ISSUE TITLE
Integration with CrewQ

### ISSUE THREAD

**Issue by fingerboxes** [magico13/KCT#45]
Hey, so I just noticed that CrewQ breaks with KCT. 

What I'm doing right now is keeping a parallel record which indicates if a crew is on vacation, but KCT doesn't know how to look for it. I would prefer to simply set their RosterStatus to an extra value, but that might bring up some other issues.

Do you have an existing compatibility reflection boilerplate code or method? Just need to call CrewQ.instance.SuppressCrew() before populating your crew selection window, and call CrewQ.instance.ReleaseCrew() afterward.

**Comment by magico13** [comment]
It sure ain't pretty since I really need to clean up the code that handles seeing who's available so it isn't called 14 times in a row, but the latest commit/dev build should at least work with CrewQ now. I haven't tested it yet though.

**Comment by fingerboxes** [comment]
Alright. I'm working on updating CrewQ right now, next release should have a better sorted list to use a data source. I'll probably roll suppress/unsuppress into accessing that data source, so that should clean things up. (Pull the data, hold onto it during the entire crew selection process, done).

**Comment by magico13** [comment]
Yeah, I'm going through my code right now to make sure it only asks for the available crew when it really needs it, instead of asking for it multiple times within the same code block. There are a few places where I ask for it when I don't 100% need to, but it's infrequent enough that it shouldn't be a performance issue and helps keep things in sync.

**Comment by magico13** [comment]
I tried to test it but couldn't get Jeb to be forced into vacation. I was probably doing flights that were too short, since I was doing a standard first launch in a new career game. If you get a chance to test it, let me know how it goes.

**Comment by fingerboxes** [comment]
Yea, I think CrewQ has more profound problems ATM than just this. I need to actually PLAY the game a bit to test, rather than just running through my list of test-cases.
