### ISSUE TITLE
persist options on crew selection screen

### ISSUE THREAD

**Issue by fingerboxes** [magico13/KCT#48]
'Small feature request please, is there any chance of making "random selection" and "automatically hire new applicants" at the launch screen, (or whatever they are called... the two littble boxes that appear when you select the crew") - persistent?'

I'm going to be working on this area when I finish up the CrewQ integration; I can take care of it?

**Comment by magico13** [comment]
If you really want. All that needs to be done is adding two more booleans to the settings, then reading from that. I can actually do it pretty quickly, maybe tonight when I get home.

**Comment by fingerboxes** [comment]
I'm procrastinating.

**Comment by magico13** [comment]
Haha, well if you really want to then feel free to. If you're feeling really bored, you can try to figure out why recovering to the inventory (from the launchpad) results in weird crashes upon relaunching the vessel. I think the flightstate isn't being properly set, so the ship is "duplicated". I haven't had enough time to take a look at it.
