### ISSUE TITLE
Math parser l((1)+1) error

### ISSUE THREAD

**Issue by supermerill** [magico13/KCT#57]
I have a error when i try the formula 100*l((2*[u])+100) in EffectivePartFormula
but it worked with 100*l( (2*[u])+100)
build #99 windows 32b

**Comment by magico13** [comment]
You appear to be missing a multiplication sign. Might be the github parser turning it into italicized text. I can't quite tell what you were trying to do. You can use \ to escape text, or can use the code formatting with 4 ` marks or putting 4 spaces in front.

I think you tried to do 100\*l(2\*[U]+100), correct? "u" is not a valid variable, it must be U (they're case sensitive. For some formula the lower case means something different from upper case). Try it exactly how I've written it and let me know if that works.

**Comment by supermerill** [comment]
It's just the parser that crash if i write l(( instead of l( (
yes, my example is bad.
with 100*l((2+[U])*3) it's also crashing:
[LOG 08:24:34.191] [KCT] fn: l sub: (2+1
[LOG 08:24:34.194] [KCT] (2+1)=(2+1)=3
[EXC 08:24:34.212] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: startIndex
	System.String.Substring (Int32 startIndex)
	KerbalConstructionTime.KCT_MathParsing.ParseMath (System.String input, System.Collections.Generic.Dictionary`2 variables)
	KerbalConstructionTime.KCT_MathParsing.ParseMath (System.String input, System.Collections.Generic.Dictionary`2 variables)
	KerbalConstructionTime.KCT_MathParsing.GetStandardFormulaValue (System.String formulaName, System.Collections.Generic.Dictionary`2 variables)
	KerbalConstructionTime.KCT_Utilities.GetBuildTime (System.Collections.Generic.List`1 parts, Boolean useTracker, System.Collections.Generic.Dictionary`2 inventory)
	KerbalConstructionTime.KCT_Utilities.GetBuildTime (System.Collections.Generic.List`1 parts, Boolean useTracker, Boolean useInventory)
	KerbalConstructionTime.KCT_Utilities.RecalculateEditorBuildTime (.ShipConstruct ship)
	KerbalConstructionTime.KerbalConstructionTime.EditorRecalculation ()

with build #99

**Comment by magico13** [comment]
No, it's definitely a bug. You can see where it says "fn: l sub: (2+1" that it isn't including the closing parenthesis, or, more precisely, is erroneously including the opening parenthesis. Should be a simple fix.

**Comment by magico13** [comment]
Should be fixed in the latest build hopefully. I did a quick test and things appeared to work properly.

**Comment by supermerill** [comment]
it work! thank you.
