### ISSUE TITLE
Resources are not handled consistently (vab preview vs real build)

### ISSUE THREAD

**Issue by supermerill** [magico13/KCT#58]
When building a vessel with only a fuel tank:
The preview building time use [C] = 'part cost' - 'resource cost'
But the real building time use [C] = 'part cost'
(tested with a fuel tank with cost  = 2*resource cost, EffectivePartFormula=[C], BPFormula = [E]*[O]
 => time for building  = 2* time preview in vab)
build #99 windows 32b

**Comment by magico13** [comment]
Confirmed and should be fixed now by including fuel costs by default. Might add a [c] variable to represent dry cost.

**Comment by supermerill** [comment]
>> iMight add a [c] variable to represent dry cost.
please!
