### ISSUE TITLE
Simulation Overhaul

### ISSUE THREAD

**Issue by magico13** [magico13/KCT#6]
Simulations need some work and I want to try to get that in version 1.1.
I will likely use this space for brainstorming. Conversation within the thread, starting primarily with [this post](http://forum.kerbalspaceprogram.com/threads/92377-0-25-Kerbal-Construction-Time-1-0-3-%2810-17-14%29-Unrapid-Planned-Assembly?p=1483680&viewfull=1#post1483680) is the major source of inspiration.
TODO:
Start simulations landed on other bodies
Purchase upgrades for better "hardware" and simulation packages.
Rework how time works to use an actual formula instead of being random (quadratic? sub-quadratic [ie exponent=1.2]?)
Use real time as opposed to in-game time?

There's more but I don't feel like listing everything right now.

**Comment by magico13** [comment]
This will probably be handled by @fingerboxes releasing HoloDeck, which is pretty similar to (if not better than) what I had planned anyway. When that happens, KCT will no longer have the simulation option by default but will instead require HoloDeck for that functionality. In CKAN it will be a recommended, but not required mod (same as StageRecovery).

HoloDeck will need an API of its own, btw, since other mods than KCT will want to integrate with it (namely TestFlight, but it might be that HoloDeck instead adds support for TestFlight, rather than the other way around). But that's up to @fingerboxes.

**Comment by ergthbeb** [comment]
In the 1.04 update, simulations are no longer available from the KSP screen. It's already kinda cumbersome to have to use the KCT interface to truly launch vessels, but having to load into the VAB or SPH just to be able to simulate without magically creating vehicles on the launchpad is a deal breaker. Can you bring back the functionality to launch simulations from the stock launch window?

**Comment by magico13** [comment]
That "functionality" was only there because I can't disable the GUI that pops up when you click the launchpad. It actually creates an infinite time simulation without costing anything, which is bad.

I want to create a GUI that opens when you click the pad to let you simulate any saved vessels and launch any vessels that are complete, but it hasn't been a priority. I may be able to restore the previous functionality though (despite the fact that simulations are now started in a completely different way then they used to be).

**Comment by fingerboxes** [comment]
You can kill the launchpad window once it spawns. I know I managed to do it
once, I'll see if I can dig up the code.

Hi BTW, sorry I've been MIA. Life :/

**Comment by ergthbeb** [comment]
Thanks for the response! Not trying to nag; KCT adds a nice element of realism. Keep up to good work!

**Comment by magico13** [comment]
Given that simulations no longer are part of KCT, I'm closing this. There is a mod that I had been working on to add simulations again, which is located at https://github.com/magico13/SimuLite
