### ISSUE TITLE
Research time when formula is tuned

### ISSUE THREAD

**Issue by supermerill** [magico13/KCT#61]
Using #104 win32
with ResearchFormula = -1
when researching a node : have a message "node will unlock in infinity days, NAN hours, NAN minutes"
and the node is never researched (with an infinite time...)

**Comment by magico13** [comment]
With ReasearchFormula, not NodeFormula? If so, that's a bug for sure. I'll look into it.

A quick glance in the source isn't showing that any streams got crossed. Those two formula *should* be working as intended. But, like I said, I'll look into it a bit more.

**Comment by supermerill** [comment]
mmm with further research, it's bugging even with with ResearchFormula = 1
perhaps something in the general config.
I will test with a fully clean ksp.

**Comment by supermerill** [comment]
Ok, i'm dumb
it's NodeFormula as you said.
with [N], it's to big for a float? erf.

**Comment by magico13** [comment]
Well, if it's set to "NodeFormula = [N]" and the number of Development upgrades is 0, then of course it'll take forever. That might be your issue.

**Comment by supermerill** [comment]
Oh, ok
Development upgrade.
My brain have set it to "number of node unlock", for a strange reason. I'm really confused against "node" "research" "developpement" "upgrade". 
I'm very sorry to have wasted your time

**Comment by magico13** [comment]
No worries! I realize some of it's set up in really weird ways, so I don't mind clarifying things and answering questions. Definitely not wasted time for me :)
