### ISSUE TITLE
Warp Bug

### ISSUE THREAD

**Issue by darqen27** [magico13/KCT#71]
Queue'd buildings to be upgraded and then launched a mission to minmus, warped thru the KAC alarms and when I returned to KSC none of the buildings were actually upgraded. 

This was not a simulation

**Comment by magico13** [comment]
I thought I had put in code that should prevent this issue, I even tested it in the Tracking Station, but it's obviously still happening. The upgrade should still stay in the list (at 100% complete) until you return to the Space Center, at which time it should then perform the upgrade. I'll have to do some tests myself when I get a chance and see if I can come up with a fix.

In the mean time, if you're in the Space Center scene when the upgrade is supposed to finish, it should complete properly. Alternatively, you can enable instant KSC upgrades in the settings until it's fixed.

Thanks!

**Comment by darqen27** [comment]
Thanks! 

I couldn't imagine playing without KCT, keep up the awesome work!
