### ISSUE TITLE
CraftHistory Incompatibility

### ISSUE THREAD

**Issue by magico13** [magico13/KCT#75]
The [CraftHistory](http://forum.kerbalspaceprogram.com/threads/110703-1-0-2-CraftHistory-1-4-2-06-05-2015-Including-craft-previews) mod prevents KCT from actually adding anything to the build list. Look into finding either a workaround or a way to make them compatible.

**Comment by magico13** [comment]
Looks like the [author knows](http://forum.kerbalspaceprogram.com/threads/110703-1-0-2-CraftHistory-1-4-2-06-05-2015-Including-craft-previews?p=1924122&viewfull=1#post1924122) and will be implementing a fix in the next version.

**Comment by Xarun** [comment]
I just released an update to fix this issue. :)
