### ISSUE TITLE
Add formula for simulation costs

### ISSUE THREAD

**Issue by magico13** [magico13/KCT#76]
Been meaning to do this, and doing it before presets are released makes the most sense. Might need separate formula for Kerbin landed and Everything Else, or might need to implement one-line if statements. Two formula is easier, but the if statements are more useful overall.

Additionally, if I can come up with an easy way to tell if someone is simulating *essentially* the same ship multiple times then we should provide that as a variable (so that consecutive simulations are cheaper, or more expensive, depending on playstyle+point of view). Either a) check if the editor scene has been reloaded since the last simulation (potentially an issue if they add a giant booster through subassemblies), or b) compare BP values and have a small margin for minute changes.

Or, we allow ANY number of changes but as long as you don't leave the editor completely the counter keeps going up. Would make it more efficient to test multiple craft in one sitting. Maybe provide both as options, single craft based on BP and single editor session based on if the scene has changed.

**Comment by futrtrubl** [comment]
Perhaps have sim cost decrease with the amount of science done around that body. Not sure how you would handle mods that add science experiments.

**Comment by magico13** [comment]
I can see about adding something like that in as a variable. If I can find an easy way of getting the amount of science done, and the total amount of science available, for a particular body then I can just pass the percentage through.

I wasn't planning on doing too much with simulations this update, so I don't want to delay the release too much by working on this stuff, since I haven't had much time recently anyway, so we'll see how much I get done on this. I might take a look at simulations further later on if HoloDeck still isn't up to speed yet.

**Comment by futrtrubl** [comment]
No rush. It would be a nice option but nothing needed.
