### ISSUE TITLE
build#121 cosmetic request.

### ISSUE THREAD

**Issue by Rodhern** [magico13/KCT#80]
I create a new career with a 'fresh install' of KCT#121.
I select "1 - Choose a Preset", and the default preset is selected automatically.
I want to "Save as New Preset".
When filling out Preset name the window flickers _while typing_.
It only flickers at this first occasion, possibly because the "Choose a Preset or Spend Upgrades" is visible underneath? It is unfortunate that the first time you see the dialog is exactly the time it is 'ugly' flickery.

**Comment by Rodhern** [comment]
Moving request to dev. forum thread.

**Comment by magico13** [comment]
I'll actually leave this open to remind me to take a look at it. The one downside of the dev thread is that if it moves too quickly it can be easy to lose bug reports in the midst. Thankfully it doesn't move too quickly and I read through all the posts again when I start bug fixing, but extra reminders are helpful.
