### ISSUE TITLE
Science rates question/ideas

### ISSUE THREAD

**Issue by NathanKell** [magico13/KCT#85]
Am I perceiving things correctly that the science rate is split amongst all researching techs? If so, I'd suggest doing something like the VAB/SPH, where unlocking the R&D center adds more rates, and/or an ability to distribute your rate amongst the nodes you are currently researching.

(If the science rate is just applied per node, i.e. any unlocking node unlocks at the science rate, then you can effectively increase your rate by unlocking multiple nodes at once)

EDIT: I was perceiving wrong, it's the latter. So yeah, that means you can effectively double your science rate by researching two nodes at a time...

**Comment by magico13** [comment]
Your edit is correct. Is that the way you want it to be, or are you asking for something different? I might be able to change up the formulas some to allow for both options (FIFO or all at once)

**Comment by NathanKell** [comment]
I'd definitely like it to be configurable, since I'm trying to represent upgrade points as "staff on your space program" which can be split between scientists (R&D) and engineers/payload integrators/etc (VAB/SPH), which means the scientists should only be Sciencing at a single fixed rate.

...this explains why I achieved orbital techs twice as fast this round, since I split them up until 2-3 nodes :]

**Comment by magico13** [comment]
I'll add in a variable for the "position" of the node, so you can limit it to a single rate, or some number of rates, or whatever :) Might not go as far in the GUI as I do with the VAB/SPH, so it'll still appear as one rate in the GUI.

**Comment by NathanKell** [comment]
Oooh, awesome. Makes sense. The only other issue with that is being able to alter position in the Tech tab, as otherwise once you commit to a node that will always be in the 'first' place.

**Comment by magico13** [comment]
Should be able to add some buttons for that as well. Might only have them appear if the rates aren't all identical.

**Comment by magico13** [comment]
Applying for Experiementals, otherwise I'd be implementing this right now :P

**Comment by NathanKell** [comment]
Hah! :)

**Comment by magico13** [comment]
Implemented. Didn't get a chance to test fully as I need to go to bed so I can wake up in time for work tomorrow. Buttons should appear if the rate isn't the same for all nodes, and shouldn't appear if the rate is the same. Use [I] for the index (capital "i"). Negative or zero should disable it.

Once again, not fully tested. You'll have to force a recalculation of the rates by changing the scene after changing the formula in-game.
