### ISSUE TITLE
Science/day display

### ISSUE THREAD

**Issue by NathanKell** [magico13/KCT#87]
When this is much less than 1, it'd be nice if it instead displayed science per year.
I ask because in RP-0 you often have rates like 10 sci/year, which is...very small in per-day units.

**Comment by NathanKell** [comment]
(It's also very *long* in per-day units; it'd be nice to use, say, N3 formatting.)

**Comment by magico13** [comment]
I'll get this done tonight and then will likely release so that KCT's not too far behind RP-0. I would have preferred a simultaneous release (or KCT a bit first) but it's alright. Hopefully there aren't too many issues with people using the older KCT with RP-0 for a day or two.

**Comment by NathanKell** [comment]
Ack! Super sorry about that! I'll be on the road today and then have poorer net access and wanted to get something out for folks.
I can say that I've been testing extensively with old-KCT and it's working fine...

**Comment by magico13** [comment]
It's no issue, I'd just like to get those features out for anyone who's playing with RP-0. The sudden transition from the old system to the new one might be a bit jarring in the middle of a career.

**Comment by NathanKell** [comment]
It will take a new career anyway since we'll have to rebalance contacts
too,  and some part prices

Sent by my thumbs, slowly.

**Comment by NathanKell** [comment]
@magico13 Sorry, keep forgetting to mention this. Is it possible to (a) increase the width one more character, and (b) display science/year rather than science/day, perhaps by cfg setting? (Because with things taking so long in RP-0, even when science/day is > 0.5, it's still more useful to have science/year as a display).
If that's tough, maybe just (a) and swapping to science/year if science/day is less than 1?

**Comment by NathanKell** [comment]
(I mention because clicking 'upgrade' does not lead to visual changes, with the display set to only the decimal width it is, making people think it doesn't do anything--it takes 4 or 5 clicks to show up)

**Comment by magico13** [comment]
I was noticing that as well and was planning on making it switch to year if it's below 0.1 science per day. Currently it switches if it's below 0.001, which is silly because it only displays two decimals. At some point I think I had it displaying 3 and then I switched to two without fixing it everywhere.

I'll reopen this until I get that fixed.

**Comment by NathanKell** [comment]
Yep, I think 3 decimals will be enough, as of now RP-0 does 0.004 science/day per point. Thanks!

**Comment by magico13** [comment]
Would you prefer 3 decimals, or per year? The code's already in to display per year, I just need to adjust the cutoff to something more sensible. 1.46 science per year might be a little more intuitive than 0.004 science per day. Then when the rate gets high enough I can have it flip back to per day (either 0.1 per day or 0.01 per day, I'm not picky about which, so if you have a preference let me know).

If you'd just prefer 3 decimals, I can do that instead and then not have it switch between year and day

**Comment by NathanKell** [comment]
Nono, I do like the switching. I'm just saying your switching threshold of 0.1/day works when there's three decimals, rather than a higher threshold (I was thinking a threshold of 1 per day originally)

**Comment by NathanKell** [comment]
EDIT: For complete clarity, IMO the best is:
3 decimal places
<0.1/day -> display per year, else display per day.

**Comment by magico13** [comment]
Alright, sounds good to me. I'll fix that up tonight then along with the Kerbin/Earth thing :)
