### ISSUE TITLE
Make rollback from Launchpad more accessible

### ISSUE THREAD

**Issue by ccaccb** [magico13/KCT#90]
Until I read somewhere that it's possible to roll back a craft from launchpad by pressing ALT I didn't know you could do that.
And so I had to recover and re-build a craft every time I made a mistake (that I didn't catch in simulation).

All other features of this mod are super easy to understand. I didn't once look into the manual.
Your mods interface is really well designed.
So is it possible to make the roll-back feature available through a button next to the craft?
Maybe use a [*] like vessels currently under construction, with just the option to roll back.
That way other people won't miss that feature.

**Comment by magico13** [comment]
There was a period of time when the * menu was available there, but I should add it back. I know it doesn't help now, but you can also force a rollback by rolling something else out (even a tiny 1 part ship) which likely would have been way faster than recovering+rebuilding. Recovering to storage also would have been faster but might have messed up the vessel.

I'll add this to my to-do list for next update. It'll likely be in a small 1.2.1 version

**Comment by ccaccb** [comment]
Awesome. Keep up the good work :-)

**Comment by magico13** [comment]
This was added in 1.2.1 by the way, and I just forgot to close this then.
