### ISSUE TITLE
Science rate based on position weirdness

### ISSUE THREAD

**Issue by NathanKell** [magico13/KCT#94]
With this node formula
NodeFormula = (5+([N]*1.5)) / 86400 / 365 * sign(-[I]) * (1+([R] * 0.5))

On first unlocking multiple nodes at once on the R&D screen, all nodes start to progress at the same rate. After a quit and relaunch of KSP, however, only the first node is progressing and the others have arrows.

**Comment by magico13** [comment]
A scene change should be all that's needed to correct that, but I'm not sure why it'd even be happening in the first place. When you first purchase the second node, what amount of time does it say for how long it will take to unlock (in the top left corner). It should say infinity.

If you purchase a node or two, then restart KSP, then purchase another node, does the new node also start researching right away (despite being at the end of the list)?

I'll test these tonight, so you don't have to, but if you get a chance to test them I'm curious what the results are.

**Comment by NathanKell** [comment]
Finishing supper, I'll give it a look. The conditions were:
1. Have an existing RP-0 career
2. Have a single node being researched.
3. Load the save, go to R&D and unlock a bunch of other nodes to (I thought) queue them up.
4. On switch back to KSC, all four techs have ETAs and are progressing at one second per second.

I didn't think to try a scene change, just quit and restarted KSP and they were working properly again.

I'll try loading an earlier save and repeating, see if I can repro (and check scene switches).
